### ISSUE TITLE
Issue using library on text containing colon (:)

### ISSUE THREAD

**Issue by Hajiri-Moez** [maize-tech/laravel-encryptable#18]
Encrypting a string already containing a colon **:** causes an issue when decrypting it.
It always throws `Maize\Encryptable\Exceptions\UnserializationException`

```php
<?php
use Maize\Encryptable\Encryption;     

$e = Encryption::php()->encrypt("test:string"); 
$p = Encryption::php()->decrypt($e);

```

**Comment by MathieuLopes** [comment]
+1 Same problem

**Comment by riccardodallavia** [comment]
Dear all, thank you for reporting the issue.
I just merged a PR that fixes it, will make a release right now!
